version: '3'

services:
  pymud:
    container_name: pymud
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNSTRING=mongodb://pymud:MKWoTw2NyksLk3Xd77ckiCBe@mongodb
    restart: always
    networks:
      - web

  mongodb: # TODO: make this use a volume to actually persistently store data
    container_name: mongodb_pymud
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pymud
      - MONGO_INITDB_ROOT_PASSWORD=MKWoTw2NyksLk3Xd77ckiCBe
    ports:
      - "27017:27017" # Disable in prod, used for debugging
    networks:
      - web

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/templates:/etc/nginx/templates
    networks:
      - web

  snekbox:
    container_name: snekbox
    image: ghcr.io/python-discord/snekbox
    privileged: true
    #ipc: none
    #tty: true
    networks:
      - web

networks:
  web:
    external: true
