version: '3'

services:
  pymud:
    container_name: pymud
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONGODB_CONNSTRING=mongodb://pymud:MKWoTw2NyksLk3Xd77ckiCBe@mongodb
      - SNEKBOX_API=http://snekbox:8060
      - FASTIFY_LOGGER=false
    depends_on:
      - mongodb
      - snekbox
    networks:
      - web

  mongodb:
    container_name: mongodb_pymud
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pymud
      - MONGO_INITDB_ROOT_PASSWORD=MKWoTw2NyksLk3Xd77ckiCBe
    ports:
      - "27017:27017" # Either do not allow access via firewall rules or remove in prod
    networks:
      - web
    volumes:
      - pymud_mongodb_data:/data/db

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - pymud
    networks:
      - web

  snekbox:
    container_name: snekbox
    image: ghcr.io/python-discord/snekbox
    restart: unless-stopped
    privileged: true
    #ipc: none
    #tty: true
    networks:
      - web

networks:
  web:
    external: true

volumes:
  pymud_mongodb_data:
